### ISSUE TITLE
node_modules are also getting installed with react-native-contacts-wrapper

### ISSUE THREAD

**Issue by deepmehtait** [LynxITDigital/react-native-contacts-wrapper#4]
When we do `npm install react-native-contacts-wrapper --save` it will also have node_modules folder which will give error of duplicate modules conflicting with react-native modules. Once I removed node_modules from your plugin it started working. 
<img width="824" alt="screen shot 2016-09-14 at 12 24 07 pm" src="https://cloud.githubusercontent.com/assets/8682058/18526638/32ef1856-7a76-11e6-9261-20530995eff8.png">

**Comment by Proyoyo** [comment]
Hi there, try using npm3. It should delete the duplicate node_modules folder automatically.

**Comment by deepmehtait** [comment]
@Proyoyo I am using `npm 3.10.3`

**Comment by Proyoyo** [comment]
We can't reproduce this issue. We're using npm 3.10.7

**Comment by JaxGit** [comment]
What version of contacts-wrapper were you using? 
Version 0.1.2 was [wrongly dependent](https://github.com/LynxITDigital/react-native-contacts-wrapper/commit/5620779d5297f72d0a97b0d35899c3d979cee71f) on react 0.14.8 and react-native 0.24.1 which would cause duplicate modules conflicting, and had been fixed on [0.1.3](https://github.com/LynxITDigital/react-native-contacts-wrapper/commit/bbaaa008285d8dc46fc8b6b323745495e18c212e).

**Comment by deepmehtait** [comment]
@JaxGit Thanks for suggesting to use 0.1.3. It did not downloaded duplicate dependency. Still have to fix android side code to make it work.
