### ISSUE TITLE
iOS8.4 runtime error: no suitable image found.

### ISSUE THREAD

**Issue by johnckendall** [LynxITDigital/react-native-contacts-wrapper#8]
Should this run ok in an iOS8.4 simulator?  Am I missing some setup step?  I'm getting:

```
dyld: Library not loaded: /System/Library/Frameworks/Contacts.framework/Contacts
  Referenced from: /Users/johnk/Library/Developer/CoreSimulator/Devices/1EE33EE4-FAEA-4E70-9838-F2CAB1854DE8/data/Containers/Bundle/Application/A84BD656-FFFB-48D1-91B3-908B1FE5B82B/My.app/MyApp
  Reason: no suitable image found.  Did find:
    /System/Library/Frameworks/Contacts.framework/Contacts: mach-o, but wrong architecture

```

It works fine in 9 and 10...

Update:  Getting this on the react-native-contacts-wrapper-example project as well:

```
dyld: Library not loaded: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
  Referenced from: /Users/johnk/Library/Developer/CoreSimulator/Devices/1EE33EE4-FAEA-4E70-9838-F2CAB1854DE8/data/Containers/Bundle/Application/345BAC00-1E17-404A-A37C-D77FC3FB58E3/RNContactsWrapperExample.app/RNContactsWrapperExample
  Reason: no suitable image found.  Did find:
    /System/Library/Frameworks/ContactsUI.framework/ContactsUI: mach-o, but wrong architecture

```

under iOS 8.4.  So I'm guessing this approach won't work... :-\

Update#2: Ok, got it to work.  Apparently _both_ the Contacts and the ContactsUI libraries must be added to the project and marked as optional.  This worked for both our project and the Example project cited above

Thanks

**Comment by alidawud** [comment]
Thank you! It works for me

**Comment by Kaishley** [comment]
How would I go add the libraries to the project and marked them as optional? I am stuck with this issue.

**Comment by lakhman** [comment]
I do not use this library but @johnckendall's answer works for me for a slightly different error I had relating to `UserNotifications` (with react native after integrating expo into a bare project, iOS 9 apps were crashing on boot due to the error below).

```
Reason: no suitable image found.
  Did find: /System/Library/Frameworks/UserNotifications.framework/UserNotifications: mach-o, but wrong architecture
```

I had to link _both_ `UserNotifications` and `UserNotificationsUI` and both should be marked as `optional`.
